# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92d119cde5a269b1c8be823ab3bba8c08b926f165b33fc6c021e3580418f2ba1b0f91afb5dcd9691930b48b169e7ffa8e00e241531415e38cb249fa9929c2bdc

test:
  secret_key_base: 3695d98960e0d930e0e082d59ac0f37e2fc6c5abcaa4d43979fa70f2796db495dd4da268a7f95dd6ee01d7c2b19360cdde496f3b7c4527e45c7cd61d3cd74bc5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
